import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router';
import { ArrowUpRight, Check, Play, Pause } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/react-app/components/ui/dialog';
import { SiteHeader, SiteFooter } from '@/react-app/components/SiteChrome';
import { ADD_ONS, STANDARD_FEATURES, STANDARD_PRICE, STAGING_TIERS } from '@/react-app/data/catalog';

export default function HomePage() {
  const [filmOpen, setFilmOpen] = useState(false);
  const [playing, setPlaying] = useState(false);
  const video = useRef<HTMLVideoElement>(null);
  useEffect(() => {
    const media = window.matchMedia('(prefers-reduced-motion: reduce)');
    const sync = () => { if (media.matches) video.current?.pause(); else video.current?.play().catch(() => {}); };
    sync(); media.addEventListener('change', sync);
    return () => media.removeEventListener('change', sync);
  }, []);
  useEffect(() => { if (filmOpen) video.current?.pause(); }, [filmOpen]);
  return <><SiteHeader /><main id="main">
    <section className="home-hero"><div className="wrap hero-copy"><p className="eyebrow">LUXENTRA MEDIA · NEW YORK</p><h1>Every listing.<br /><span>A lasting impression.</span></h1><p className="hero-description">Photography, films and personal branding.<br />Thoughtfully made for real estate.</p><div className="actions"><Link to="/order" className="pill pill-lime">Book a Shoot</Link><a href="#work" className="text-link">Explore the work <ArrowUpRight size={18} /></a></div></div>
    <div className="hero-film"><video ref={video} muted loop playsInline preload="metadata" poster="/work/film-still-01.jpg" onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} aria-label="Silent preview of the featured property film"><source src="/hero-video.mp4" type="video/mp4" /></video><div className="film-bottom"><span>Spaces. Seen differently.</span><button className="round-control" aria-label={playing ? 'Pause background film' : 'Play background film'} onClick={() => { if (playing) video.current?.pause(); else video.current?.play().catch(() => {}); }}>{playing ? <Pause size={18} /> : <Play size={18} />}</button></div></div></section>
    <section id="work" className="section wrap"><div className="section-heading"><div><p className="eyebrow">THE WORK</p><h2>Step inside.</h2></div><p>A closer look at our featured property film.<br />From the first approach to the smallest detail.</p></div><div className="work-grid"><button className="work-card work-main" onClick={() => setFilmOpen(true)} aria-label="Watch the featured property film"><img src="/work/film-still-01.jpg" alt="Terrace with a living wall and floor-to-ceiling windows, still from the featured film" width="1920" height="1080" loading="lazy" /><span className="work-overlay"><span>Featured property film</span><span className="round-control"><Play size={20} /></span></span></button><div className="work-side"><figure><img src="/work/film-still-02.jpg" alt="Kitchen and dining space, still from the featured film" width="1920" height="1080" loading="lazy" /><figcaption>Room to explore.</figcaption></figure><figure><img src="/work/film-still-03.jpg" alt="Staircase and tall windows, still from the featured film" width="1920" height="1080" loading="lazy" /><figcaption>Details worth seeing.</figcaption></figure></div></div><p className="caption">Stills from the featured film.</p></section>
    <section id="services" className="section soft-section"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">WHAT WE CREATE</p><h2>One creative team.<br />Every angle covered.</h2></div></div><div className="service-grid"><article><span className="service-index">01 / PHOTOGRAPHY</span><h3>Make the first<br />look count.</h3><p>Interior and exterior photography, twilight imagery and floor plans. Ready for your listing.</p><a className="text-link" href="#package">Explore photography <ArrowUpRight size={18} /></a></article><article className="service-dark"><span className="service-index">02 / FILM</span><h3>Give the space<br />a story.</h3><p>Walkthrough films and aerial perspectives that show how a property feels and connects.</p><button className="text-link" onClick={() => setFilmOpen(true)}>Watch the film <Play size={17} /></button></article><article><span className="service-index">03 / PERSONAL BRANDING</span><h3>Be the agent<br />they remember.</h3><p>Short-form content shaped around you, from the first idea and script to filming and editing.</p><Link className="text-link" to="/order?addon=reel">Explore branding <ArrowUpRight size={18} /></Link></article></div></div></section>
    <section id="package" className="section wrap"><div className="package-layout"><div><p className="eyebrow">THE LISTING ESSENTIALS</p><h2>Your next listing.<br />Ready to launch.</h2><p className="section-description">The Standard Listing Media Package brings your photography and floor plans together in one straightforward booking.</p><p className="package-price">${STANDARD_PRICE}<span>per package</span></p><Link to="/order" className="pill pill-dark">Build your package</Link></div><div className="inclusions"><h3>All the essentials. Included.</h3><ul>{STANDARD_FEATURES.map(feature => <li key={feature}><Check size={19} aria-hidden="true" />{feature}</li>)}</ul><p>High-resolution and MLS-optimized files. Full usage rights for listing purposes.</p></div></div></section>
    <section id="addons" className="section soft-section"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">MAKE IT YOURS</p><h2>A little more.<br />A different perspective.</h2></div><p>Choose the extras your listing needs.<br />See your total before sending a request.</p></div><div className="upgrade-grid">{ADD_ONS.map(addon => <Link to={`/order?addon=${addon.id}`} className="upgrade-card" key={addon.id}><h3>{addon.name}</h3><p>{addon.description}</p><div><span>${addon.price}{addon.id === 'flyer' && <small> for one</small>}</span><ArrowUpRight size={22} aria-hidden="true" /></div></Link>)}<Link to="/order?addon=staging" className="upgrade-card"><h3>Virtual Staging</h3><p>Digitally furnished rooms to help buyers picture the possibilities. Delivered within 24 hours.</p><div><span>From ${STAGING_TIERS[0].price}</span><ArrowUpRight size={22} aria-hidden="true" /></div></Link></div><Link to="/special" className="partnership-link"><span><strong>Listing every week?</strong> Explore partnership pricing for agents and teams.</span><ArrowUpRight size={22} /></Link></div></section>
    <section className="section wrap"><div className="section-heading"><div><p className="eyebrow">FROM SHOOT TO LISTING</p><h2>Easy from the start.</h2></div></div><div className="process-grid">{[['01', 'Tell us about the property.', 'Choose your media and preferred shoot date. We’ll get back to you within 24 hours to confirm the details.'], ['02', 'We take care of the shoot.', 'Our team captures the space and prepares the photography, films and extras you selected.'], ['03', 'Your media. Ready to share.', 'Download your files through a private branded gallery, with formats ready for your listing.']].map(([n,title,description]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section className="closing"><div className="wrap"><img src="/brand/symbol-lime.png" width="58" height="58" alt="" /><h2>Let’s make your<br />next listing stand out.</h2><div className="actions"><Link to="/order" className="pill pill-lime">Book a Shoot</Link><Link to="/about" className="text-link">Meet the team <ArrowUpRight size={18} /></Link></div></div></section>
  </main><SiteFooter /><Dialog open={filmOpen} onOpenChange={setFilmOpen}><DialogContent className="film-dialog"><DialogTitle>Featured property film</DialogTitle><DialogDescription>Explore the property in the full film.</DialogDescription><video src="/hero-video.mp4" controls playsInline preload="metadata" poster="/work/film-still-01.jpg" aria-label="Featured property film" /></DialogContent></Dialog></>;
}
